rd /s/q bin
mkdir bin
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\Request.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\HelloRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\TextRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\VoiceRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\ImageRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\LocationRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\LinkRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\EventRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\request\UnknowRequest.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\response\Response.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\response\TextResponse.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\response\MusicResponse.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\response\ArticleResponse.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\response\ErrorResponse.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\sdk\WhistleChart.java
javac -sourcepath src -encoding utf-8 -d bin -classpath lib/dom4j.jar;lib/jdom;lib/jetty-continuation.jar;lib/jetty-http.jar;lib/jetty-io.jar;lib/jetty-security.jar;lib/jetty-server.jar;lib/jetty-servlet.jar;lib/jetty-util.jar;lib/jetty-webapp.jar;lib/jetty-xml.jar;lib/servlet.jar;lib/json.jar src\ruijie\whistle\lightapp\demo\MyLightApp.java
rd /s/q %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes
mkdir %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\demo
mkdir %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\sdk
mkdir %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\request
mkdir %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\response
copy bin\ruijie\whistle\lightapp\demo\*.class %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\demo\. /y
copy bin\ruijie\whistle\lightapp\sdk\*.class %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\sdk\. /y
copy bin\ruijie\whistle\lightapp\request\*.class %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\request\. /y
copy bin\ruijie\whistle\lightapp\response\*.class %CATALINA_HOME%\webapps\lightapp\WEB-INF\classes\ruijie\whistle\lightapp\response\. /y
